#!/bin/sh
# Generate runtime configuration from environment variables
# This runs at container startup, allowing runtime configuration of the SPA

# Default values if not provided
API_URL="${VITE_API_URL:-http://api.localhost/agents}"
INNGEST_DEV_URL="${VITE_INNGEST_DEV_URL:-http://inngest.localhost}"

# Generate the runtime config file
cat > /usr/share/nginx/html/config.js << EOF
// Runtime configuration - generated at container startup
// Do not edit this file directly; set environment variables instead
window.__AGENTOPS_CONFIG__ = {
  apiUrl: "${API_URL}",
  inngestDevUrl: "${INNGEST_DEV_URL}",
};
EOF

# Ensure nginx can read the file
chmod 644 /usr/share/nginx/html/config.js

echo "Generated runtime config:"
cat /usr/share/nginx/html/config.js

# Start nginx
exec nginx -g 'daemon off;'
