# Tempo Configuration for AgentOps
# Receives OTLP traces from agent-server and other services

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

# Enable multi-tenancy if needed, otherwise use single-tenant mode
multitenancy_enabled: false

# Distributor configuration
distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

# Ingester configuration
ingester:
  trace_idle_period: 10s
  max_block_bytes: 1048576  # 1MB
  max_block_duration: 5m

# Compactor configuration
compactor:
  compaction:
    block_retention: 72h  # 3 days retention

# Storage configuration - local filesystem for dev
storage:
  trace:
    backend: local
    local:
      path: /var/lib/tempo/traces
    wal:
      path: /var/lib/tempo/wal

# Metrics generator for span metrics
metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/lib/tempo/generator/wal

# Query frontend configuration
query_frontend:
  search:
    max_duration: 0  # No limit on search duration
